version: '3'
services:
    python:
        build: ./docker/python
        container_name: python
        volumes:
            - ./src:/var/www/html
        ports:
            - "5000:80"
        tty: true
